# Generated by Django 5.0.3 on 2024-04-01 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('discount_residential', models.FloatField(verbose_name='Desconto Residencial')),
                ('discount_commercial', models.FloatField(verbose_name='Desconto Comercial')),
                ('discount_industrial', models.FloatField(verbose_name='Desconto Industrial')),
            ],
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='consumption',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='distributor_tax',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='document',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='consumer',
            name='address',
            field=models.CharField(default=None, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='consumption1',
            field=models.FloatField(default=None, verbose_name='Consumo Mês 1 (kWh)'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='consumption2',
            field=models.FloatField(default=None, verbose_name='Consumo Mês 2 (kWh)'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='consumption3',
            field=models.FloatField(default=None, verbose_name='Consumo Mês 3 (kWh)'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='email',
            field=models.EmailField(default=None, max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='tariff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calculator.tariff', verbose_name='Tarifa'),
        ),
    ]
