# Generated by Django 5.0.3 on 2024-04-01 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_tariff_remove_consumer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='consumption1',
            field=models.FloatField(verbose_name='Consumo Mês 1 (kWh)'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='consumption2',
            field=models.FloatField(verbose_name='Consumo Mês 2 (kWh)'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='consumption3',
            field=models.FloatField(verbose_name='Consumo Mês 3 (kWh)'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.tariff', verbose_name='Tarifa'),
        ),
    ]
