# Generated by Django 5.0.3 on 2024-04-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_consumer_address_alter_consumer_consumption1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='cep',
            field=models.CharField(default=None, max_length=9),
        ),
    ]
